[CEP-6] Add support for customizable ordersets and trigger mechanisms
ohcnetwork/legacy-docs pull request #33
Opened 2024-08-01 08:25 UTC by sainak

This pull request adds support for customizable clinical ordersets within the CARE system. It introduces triggerable ordersets that can be automatically triggered based on predefined conditions such as patient diagnosis or lab results. The feature also allows customization of ordersets to cater to the specific protocols of various healthcare facilities or departments. The implementation includes the addition of rulesets and ordersets models, as well as the implementation of the orderset trigger mechanism through signals and manual triggers.

2024-10-07 22:30 UTC, bodhish requested changes
I am unable to fully understand this feature, can we improve the docs?

2024-10-07 22:30 UTC, bodhish commented on docs/care/CEP/Draft/0006-customizable-ordersets.md
> +We propose to introduce support for customizable clinical ordersets within the CARE system to enhance decision-making and standardize care processes. This feature should include a mechanism to trigge
Can you expand the requirments? / Ask Product to expand?

2024-12-06 06:19 UTC, gigincg commented
@sainak Ping

2025-03-17 15:48 UTC, Bhavna1312 commented
Hi, I’m new to this project and would like to contribute. Could someone guide me on how to get started with this issue?

2025-03-18 09:12 UTC, gigincg commented
@Bhavna1312 This issue is on hold at the moment and will not be assigned until further clarity is built on the requirements

2025-04-30 17:49 UTC, closed without merging