Add DevOps Docs
ohcnetwork/legacy-docs pull request #57
Opened 2024-09-26 14:45 UTC by tellmeY18

solves #48

2024-09-30 19:53 UTC, bodhish commented
@gigincg can you review this. 
I am not sure why we need docs for the CI files. A few of it looks redundant.

2024-09-30 20:06 UTC, bodhish requested changes
I have just looked into the digital ocean docs and its incomplete.

2024-09-30 20:06 UTC, bodhish commented on docs/devops/Deploy/Care/digitalOcean/index.md
> +## Setting up VPC
Where have we documented the use of VPC requirment?

2024-09-30 20:06 UTC, bodhish commented on docs/devops/Deploy/Care/digitalOcean/index.md
> +- Choose the PostgreSQL database engine.
Where does the user find docs for the PG version?

2024-09-30 20:06 UTC, bodhish commented on docs/devops/Deploy/Care/digitalOcean/index.md
> +- Choose ideal options for the database and click on Create Database.
What are the "ideal options"?

2024-09-30 20:06 UTC, bodhish commented on docs/devops/Deploy/Care/digitalOcean/index.md
> +- Set the VPN to the one created in the previous step.
Did we create a VPN in the previous step?

2024-09-30 20:06 UTC, bodhish commented on docs/devops/Deploy/Care/digitalOcean/index.md
> +- Set bucket name and set the suitable options to create the bucket.
What are the "sutiable options" here?

2024-09-30 20:06 UTC, bodhish commented on docs/devops/Deploy/Care/digitalOcean/index.md
> +- Enable CDN for faster content delivery.
I don't see an option to enable CSN after navigating to the spaces page.

2024-09-30 20:06 UTC, bodhish commented on docs/devops/Deploy/Care/digitalOcean/index.md
> +    REACT_APP_API_URL: <care-api-url>
where do I get this URl without deploying the backend?

2024-10-07 22:19 UTC, bodhish requested changes
Lets name the files right. 
We shoudn't have files with names like `1.md`, `2.md`, `x.md` etc.

2024-10-07 22:26 UTC, bodhish requested changes
Add an Infrastructure overview. Use mermaid diagram for building diagrams. 
Example: https://deploydocs.coronasafe.network/cloud-deployment-overview/diagram

2024-10-07 22:26 UTC, bodhish commented on yarn.lock
Lets either use npm or yarn. Mixing both will be a pain.

2024-10-07 22:26 UTC, bodhish commented on docusaurus.config.ts
> +        { to: "/docs/devops/", label: "DevOps", position: "left" },
Move it up to line 71

2024-10-07 22:26 UTC, bodhish commented on docs/devops/index.md
> +
Add an introduction.

2024-10-07 22:26 UTC, bodhish commented
@dauntlessnomad @gigincg Please review the PR

2024-10-18 08:22 UTC, bodhish commented
@tellmeY18 whats the status here!!!!!

2024-10-18 12:42 UTC, tellmeY18 commented
Finishing up the last bit of changes. Will commit the changes tonight.

2024-11-06 09:53 UTC, merged

2024-11-06 09:53 UTC, gigincg commented
Merged as a base DevOps Doc. @tellmeY18 Do file an issue to clean this up to improve quality separately