add scheduling docs
ohcnetwork/legacy-docs pull request #61
Opened 2024-10-07 11:06 UTC by anroopak

2024-10-07 22:15 UTC, bodhish commented
@anroopak I think structually we should follow [PEP](https://peps.python.org/pep-0614/#copyright) layout keeping just one file per CEP

2024-10-07 22:18 UTC, bodhish requested changes

2024-10-07 22:18 UTC, bodhish commented on docs/care/CEP/Draft/0007-scheduling/scheduling.png
I think we should use `mermaid` for diagrams. It would be way easier for us to update edit it. 

[mermaid](https://docusaurus.io/docs/next/markdown-features/diagrams)

2024-10-14 13:02 UTC, anroopak commented on docs/care/CEP/Draft/0007-scheduling/scheduling.png
Updated the docs to mermaid.

2024-10-15 14:20 UTC, vigneshhari requested changes

2024-10-15 14:20 UTC, vigneshhari commented on docs/care/CEP/Draft/0007-scheduling.md
> +    vReqdata --> vAvailability["Validate Basic Request Data"]
This step seems to be duplicated.

2025-04-30 17:49 UTC, closed without merging