Care plan proposal
ohcnetwork/legacy-docs pull request #78
Opened 2024-11-15 07:44 UTC by shivankacker

2025-01-20 06:05 UTC, bodhish requested changes

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +SNOMED-CT is not yet implemented with care, so we would default to using ICD 11 diagnosis until SNOMED is configured.
We have snowmedct enabled!

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +    custodian/faciliy = FK(Facility) # wont use if we use encounter
```suggestion
    patient = FK(Patient)
    encounter = FK(Encounter) 
    custodian= FK(FacilityOrganization) 
```

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +    addresses = FK(ICD11Diagnoses) #or SNOMED going forward
This will be our condition right 🤔, also is it doing to be 1 or many?

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +    notes = TextField()
Notes are optional

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +    activity_task = FK(Task)
Where is `Task` defined 🤔

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +    activity_service_request = FK(ServiceRequest)
Shouldn't this be polymorphic field? 🤔

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +I am not very sure about how the Task, MedicationRequest and ServiceRequest would look like. We can directly connect these models to the care plan instead of having the Activity model if it is more f
We have UI for all of these now

2025-01-20 06:05 UTC, bodhish commented on docs/care/CEP/Draft/0012-careplan.md
> +    permitted_groups = ArrayField(choices=PermissionGroups) # to specify if certian groups (like nurses) can update the goal or not.
should be organizations

2025-01-22 08:01 UTC, shivankacker commented on docs/care/CEP/Draft/0012-careplan.md
> +SNOMED-CT is not yet implemented with care, so we would default to using ICD 11 diagnosis until SNOMED is configured.
Yup, this was made before we did that

2025-01-22 08:01 UTC, shivankacker commented on docs/care/CEP/Draft/0012-careplan.md
> +    addresses = FK(ICD11Diagnoses) #or SNOMED going forward
Many

2025-01-22 08:03 UTC, shivankacker commented on docs/care/CEP/Draft/0012-careplan.md
> +    activity_task = FK(Task)
based on presumtption of Task being predefined. Should I include Task and ServiceRequest in the scope?

2025-01-22 08:03 UTC, shivankacker commented on docs/care/CEP/Draft/0012-careplan.md
> +    activity_service_request = FK(ServiceRequest)
Will be only one of either

2025-01-22 08:04 UTC, shivankacker commented on docs/care/CEP/Draft/0012-careplan.md
> +I am not very sure about how the Task, MedicationRequest and ServiceRequest would look like. We can directly connect these models to the care plan instead of having the Activity model if it is more f
Can you guide me to where to find the Task and ServiceRequest UI?

2025-04-30 17:49 UTC, closed without merging